# Generated by Django 3.2.5 on 2021-08-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race_info', '0002_direction_gender_trackcondition_tracktype_trainingcenter_weather'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': '回り', 'verbose_name_plural': '回り'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': '性別', 'verbose_name_plural': '性別'},
        ),
        migrations.AlterModelOptions(
            name='trackcondition',
            options={'verbose_name': '馬場状態', 'verbose_name_plural': '馬場状態'},
        ),
        migrations.AlterModelOptions(
            name='tracktype',
            options={'verbose_name': 'コース', 'verbose_name_plural': 'コース'},
        ),
        migrations.AlterModelOptions(
            name='trainingcenter',
            options={'verbose_name': 'トレーニング・センター', 'verbose_name_plural': 'トレーニング・センター'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': '開催地', 'verbose_name_plural': '開催地'},
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': '天気', 'verbose_name_plural': '天気'},
        ),
    ]
