version: '3'

services:
  django:
    container_name: horse-django
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - ./:/work
    ports:
      - "8080:8080"
    environment:
      # 1ならデバックモード
      SCRAPE_URL: ${SCRAPE_URL}
      DEBUG: 1
    command: /bin/bash -c "python backend/manage.py runserver 0.0.0.0:8080"
  next-js:
    container_name: horse-next-js
    build:
      context: ./
      dockerfile: docker/next-js/Dockerfile
    ports:
      - "3000:3000"
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
    command: sh -c "npm run dev"