# Generated by Django 4.2 on 2023-05-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField()),
                ('race_date', models.DateField()),
                ('venue', models.IntegerField(choices=[(1, '札幌'), (2, '函館'), (3, '福島'), (4, '新潟'), (5, '東京'), (6, '中山'), (7, '中京'), (8, '京都'), (9, '阪神'), (10, '小倉')], null=True)),
                ('race_class', models.IntegerField()),
                ('race_number', models.IntegerField()),
                ('track_type', models.IntegerField(choices=[(1, '芝'), (2, 'ダ')], null=True)),
                ('distance', models.IntegerField()),
                ('track_condition', models.IntegerField(choices=[(1, '良'), (2, '稍'), (3, '重'), (4, '不')], null=True)),
                ('direction', models.IntegerField(choices=[(1, '右'), (2, '左'), (3, '直接')], null=True)),
                ('weather', models.IntegerField(choices=[(1, '晴'), (2, '曇'), (3, '小雨'), (4, '小雪'), (5, '雨'), (6, '雪')], null=True)),
                ('starters', models.IntegerField()),
            ],
            options={
                'verbose_name': 'レース情報',
                'verbose_name_plural': 'レース情報',
            },
        ),
    ]
