# Generated by Django 4.2 on 2023-05-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
        ('race', '0001_initial'),
        ('jockey', '0001_initial'),
        ('racing_horse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaceResult',
            new_name='RacingHorseResult',
        ),
    ]
