# Generated by Django 4.2 on 2023-05-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racing_horse', '0002_rename_raceresult_racinghorseresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racinghorseresult',
            old_name='race_id',
            new_name='race',
        ),
    ]
