# Generated by Django 3.2.5 on 2021-08-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '生産者',
                'verbose_name_plural': '生産者',
            },
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '騎手',
                'verbose_name_plural': '騎手',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '馬主',
                'verbose_name_plural': '馬主',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '調教師',
                'verbose_name_plural': '調教師',
            },
        ),
    ]
