# Generated by Django 3.2.5 on 2021-08-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0002_auto_20210802_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stallion',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': '種牡馬',
                'verbose_name_plural': '種牡馬',
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('birthday', models.DateField()),
                ('mother', models.TextField()),
                ('father_father', models.TextField()),
                ('father_mother', models.TextField()),
                ('mother_mother', models.TextField()),
                ('breeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_info.breeder')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sire', to='basic_info.stallion')),
                ('mother_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bms', to='basic_info.stallion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_info.owner')),
            ],
            options={
                'verbose_name': '競走馬',
                'verbose_name_plural': '競走馬',
            },
        ),
    ]
