# Generated by Django 3.2.5 on 2021-08-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeder',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jockey',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.TextField(),
        ),
    ]
