# Generated by Django 3.2.5 on 2021-08-04 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('basic_info', '0004_auto_20210803_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horse',
            old_name='father_father',
            new_name='father_father_id',
        ),
        migrations.RenameField(
            model_name='horse',
            old_name='father_mother',
            new_name='father_mother_id',
        ),
        migrations.RenameField(
            model_name='horse',
            old_name='mother',
            new_name='mother_id',
        ),
        migrations.RenameField(
            model_name='horse',
            old_name='mother_mother',
            new_name='mother_mother_id',
        ),
    ]
